name: Build OBS Plugin (Windows)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest  # or 'windows-2022' if you prefer a fixed image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake + Ninja
        uses: lukka/get-cmake@v3.30.3

      - name: Install OBS Studio (winget)
        shell: pwsh
        run: |
          winget install --id OBSProject.OBSStudio -e --accept-source-agreements --accept-package-agreements
          $cmakeRoot = "$Env:ProgramFiles\obs-studio\cmake"
          if (-not (Test-Path "$cmakeRoot\libobs\libobsConfig.cmake")) {
            Write-Error "OBS CMake files not found at $cmakeRoot. Install may have failed."
          }

      - name: Configure (CMake)
        shell: pwsh
        run: |
          $cmakeRoot = "$Env:ProgramFiles\obs-studio\cmake"
          cmake -S . -B build -G Ninja `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_VERBOSE_MAKEFILE=ON `
            -DCMAKE_PREFIX_PATH="$cmakeRoot" `
            -Dlibobs_DIR="$cmakeRoot\libobs" `
            -Dobs-frontend-api_DIR="$cmakeRoot\obs-frontend-api" `
            --debug-find

      - name: Build
        run: cmake --build build --config Release -v

      - name: Stage plugin
        shell: pwsh
        run: |
          $Stage="stage\obs-plugins\64bit"
          New-Item -Force -ItemType Directory $Stage | Out-Null
          Copy-Item build\*.dll $Stage -Force -ErrorAction Stop

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-plugin
          path: |
            stage/**
            build/**

