name: Build OBS Plugin (Windows)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake + Ninja
        uses: lukka/get-cmake@v3.30.3

      # Find and download the latest obs-deps win64 bundle (robust + retries)
      - name: Download OBS deps (win64)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $retries = 5
          $delay = 5
          for ($i=1; $i -le $retries; $i++) {
            try {
              $release = Invoke-RestMethod -UseBasicParsing https://api.github.com/repos/obsproject/obs-deps/releases/latest
              $asset = $release.assets | Where-Object { $_.name -match '^win64-deps-.*\.zip$' } | Select-Object -First 1
              if (-not $asset) { throw "No win64-deps asset found in latest release." }
              $zip = "$env:RUNNER_TEMP\obs-deps.zip"
              Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $zip
              New-Item -ItemType Directory -Force -Path C:\obs-deps | Out-Null
              Expand-Archive -Path $zip -DestinationPath C:\obs-deps -Force
              break
            } catch {
              if ($i -eq $retries) { throw $_ }
              Start-Sleep -Seconds $delay
            }
          }

      - name: Configure (Ninja Release)
        shell: pwsh
        run: >
          cmake -S . -B build -G Ninja
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_PREFIX_PATH="C:\obs-deps\lib\cmake"

      - name: Build
        run: cmake --build build --config Release -j

      - name: Stage install
        run: cmake --install build --config Release --prefix "${{ github.workspace }}\stage"

      - name: Upload artifact (DLL)
        uses: actions/upload-artifact@v4
        with:
          name: obs-xbox-zoom-pan-windows
          path: stage/obs-plugins/64bit/obs-xbox-zoom-pan.dll

      # Also upload logs and full stage for debugging if needed
      - name: Upload build logs and stage (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-and-stage
          path: |
            build/CMakeFiles/CMakeOutput.log
            build/CMakeFiles/CMakeError.log
            stage/**

